### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by blackCmd** [ZQPei/deep_sort_pytorch#159]
When i tried `python yolov3_deepsort.py` it returns me error : 
`RuntimeError: CUDA error: invalid device function
Segmentaion falult (core dumped)
`

How can i solved

**Comment by johannwyh** [comment]
Hey buddy, have you fixed this issue? I think it is something about the compilation of NMS module, but I really cannot figure out what is the cause.

**Comment by johannwyh** [comment]
UPDATE : if your problem is also caused by nms module and you have a torchvision >= 0.3.0, you can use torchvision.ops.nms to replace the self-compiled one.
To do this, simply replace the 8th line of `deep_sort_pytorch/detector/YOLOv3/nms/nms.py` from
```python
_nms = torch_extension.nms
```
to 
``` python
_nms = torchvision.ops.nms
```

**Comment by blackCmd** [comment]
> UPDATE : if your problem is also caused by nms module and you have a torchvision >= 0.3.0, you can use torchvision.ops.nms to replace the self-compiled one.
> To do this, simply replace the 8th line of `deep_sort_pytorch/detector/YOLOv3/nms/nms.py` from
> 
> ```python
> _nms = torch_extension.nms
> ```
> 
> to
> 
> ```python
> _nms = torchvision.ops.nms
> ```

Oh, Thank you i solved my problem.
I just followed Readme file : )
